[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
logs = { path = "../logs" }
envy = "0.4"
config = "0.11"
once_cell = "1.13.0"
serde = { workspace = true }
bitcoin = { workspace = true }

