[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
logs = { path = "../logs" }
tokio = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
ctrlc = { version = "3.1", features = ["termination"] }
